# Generated by Django 6.0.4 on 2026-05-07 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_units', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='calculator.result')),
            ],
        ),
    ]
